[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'corepack enable',
  'npm install -g pnpm@latest',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['npm run build:bff']

[start]
cmd = 'npm run start:bff'